spring:
  datasource:
    url: jdbc:postgresql://195.80.51.63:5432/task_service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080