spring:
  datasource:
    url: jdbc:postgresql://195.80.51.63:5432/task_service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
custom-properties:
  jwt:
    secret: jsonwebtokensecretphrasepneumonoultramicroscopicsilicovolcanoconiosisantidisestablishmentarianism
    issuer: ilya
  executor:
    url: https://onecompiler-apis.p.rapidapi.com/api/v1/run
    host: onecompiler-apis.p.rapidapi.com